version: '3.7'

services:
  redis:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"

  chat:
    build: .
    restart: always
    ports:
      - "8080:8080"
      - "3785:4783"
    environment:
      WAIT_HOSTS: redis:6379