version: '3.7'

services:
  redis:
    image: redis
    container_name: cache
    ports:
      - "${HOST_REDIS_PORT}:${REDIS_PORT}"

  chat:
    build: .
    restart: always
    ports:
      - "${HOST_APP_PORT}:${APP_PORT}"
    environment:
      WAIT_HOSTS: redis:${REDIS_PORT}