version: '3.7'

services:
  mysql_db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - chat_db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root #Enter here your password
      MYSQL_DATABASE: chat

  hls-rest:
    build: .
    restart: always
    ports:
      - "8080:8080"
      - "3785:4783"
    environment:
      WAIT_HOSTS: mysql_db:3306

volumes:
  chat_db:
    external: true
    name: chat_db